language: java
jdk:
- openjdk11
services:
- docker
script:
- "make all"
deploy:
- provider: script
  on:
    tags: true
  skip_cleanup: true
  script:
  - "make docker-deploy"
global:
  env:
    - secure: hu0Ar8uCCv3eIm3xd5oTBwC0fyu6QX/ip2VXNqd3/xtnACzUikrf2i9reKtAxOnMXhjXpQd+3rv/z6B7iJdbfj5R4yC2GR1ttravzf56OlesOCgrhw7x+Q2l0LJF5R84iwGFbCvgVRQ2ISU+EvkFSnVyYnRgQ0ReQK8UEoNUo/7lCCPSKfn9gANPQF0guGG8ItonUSy5YSLfoGB5jD6l0JETeuCEjAwVY2vj7MOgQvnHfBJxi//UseUTUtiP51GET/E6qGIE1fhHgu4+c3gQSUlFAK0B1i6QYcpNf5F6AF1ler0WtMzdW67AIGSXstTDlD32WTLUW5k+ERJIPRQwP1HUxMJZ48tkcQNQTpd0ca6g+jVMelU6Rc1Vq6vU9wNpn3KQ+spBpkPE8PGOqrajzbwSRxJAAE2tZ7BlQ3DoCIPHg3FDONyHy9Ey588vgfcQbNINEZofMwRmGNaxfyWS5j6TYX4EBASoq5q/82xPgWrQt24pSMVjYO3Qmnk4ngcRfBtOY2ftJIbwraBy4xqcNMKSw9ZboECcZsCnUQn+UYqYC/6dpKTuywZLnDpXpxOehiqaBZTws+04UiG9om1EISzU+ZnCJxUIkIkpIklUJykSFvfuzoaB+DlF5k+fZrtp56H4sNhZ519zWOpcwaqUxZlRkNhOmIGybpJsVXdSOf4=
    - secure: gcm3kU7bPrq6Zsdw3Y3JMLthN/8CBxNxzoFAr5n8ckHmK26FcVNLyOi3m/6SLeoAw8KGtJPpLXO/qYw68RUaC+jQPuVpC+Mgn8dq+gD+QANHdhpAiZgsD3oBt7pYnhB5hBFNnXYj7GbCVttz3VSE/HXFLQogzelVvGaUvlrfDR6vMwQe9iGCf+7RzfDh/rhIadsV0AYeUVTU7+51x4MYHmg4K85TrcPvCv2eM2+Gu6lj7sXtHpzzOuNmtNDv18rP3ebmFKMKGrQEcvGQVvjH27v+7FwSHbC4r55j5aSP94UdoTTYDH6zceS4+rEN2auCxnqrkBgCeJmFbMYw6hDCgtH8IO089NS3HjTnYp8+0Mmd9KdGlxkCSYUO4Js/m9h04s8sfLGhVuHD5EVBFifrt4oqWL6ToEQG+7Lz6Z8nKEHWlJKhNh9jwrqZirX/+uDg7OcAmgp8OlJHpQUImlXiTQGs97P89yLDPlSoDioci4EoZJ3q8u1b7nQSkuHt4SQOUtC0BT24rUrWNj1V2X9kSFmr0GpquXYlw4avEjYYA5gbceda++S96DN6iP6CCTiPpt+/exLfLh3mru/xKe/jighDPL6t8Ns4MR/UGcmusu6uJCMtJYp35Hi+ZN1eBWqkIJMVKv4BSn3oJNttVlpJbUPH5HpzABUDErpIQsmE5tU=
    - secure: NopzYN0IRFim1/YuHxdxXUAZZcLlO7NsSRCtfSKEsF5RWNhgUO7RhAgR4NoRiomm/kQ3iXDXec/RdKKUUf+yppHsGS8aoNqCHPaYIFdXzAZVH09O7gK3pLVb/nEkO8q7F1maNtEpXXeIFMQZNkOg4dkHZnDiqHInqCdi/QCxkx1iO/2zWODvQKCVIEwcacscajItDZVHHsuw00kcG9AKdx1YKNl4ZQYnmsTauC3MREZZDGDV9pKNmbL0Xljllgjqt9aneCVTjTTXHsOQu3uZ/KmI+8Dh/051/etOXggKBVRFC1lCmwm8KGUQgUmttYjnVKONuyAzqeSjPVk/Fuy+1I/2wIgmwqwyPha9mQBG1sKNSCNp3kzL9HmElyEC7V1CROqDbfPOylZgVZP64RYmnVh7PhlSVywMME5vNNn9ZgcRA22Uz90aW0cuJoN94BaoybiWW57JZOOsm2um2rt88vphRJc2ESJ7KeBkE6oEQB3EL1kK2M1J1/JFcSNxiXQLcOC/xTaIrKDMWrQjZ7Eaqf0CLHxOQxHEZ+1NwYrTbztKkNXLn81Xp+FLa1cLKUOWTHpm/u5d+zyQbK3Db4eW7OMeSpfaYIwKORm53C1o8DxISGlZBHXanm17nFqJb0tH7KmwADsOHzTEx4h34gl5hl07eaq44D4q8ffMVoRSdWA=
