language: java
jdk:
- openjdk11
services:
- docker
env:
  global:
    secure: "AaDVqWJk8xeVU0Pqn9LbkDfZljUzVALVKBKuV0RUxL8RwMdePQp+W9BvFaZTTr+Ubg6NCvWfrUSinKRvTHYYlyO6EMBZe0d24IfID7BAb1P1gjkWvgNfvvdAtRT4MWbi4olG4JmJcj7vBmqhjP9KSOLs0hQkH2Aa0OQLSELKCveH+iiV6/oKnP1qHPcOKltTlFMgNrVtUZ19noLRx38UYu4Eod1Vnj+IQFzNzvRv6NMbx3qb/KgYrgWYFJf+MG1Vym4dqyFomio3boZ+LHJMkMK1MF2mHfxtap2la+7EGrVML4jswK7oqEl+3SW8XnGSREpLSxA09u4ZBAiueefHPhlpfUyEpwcWCnnkpepwn9g/K9oLqK53A+CkENPDKMJMqPJqrP8es8cqVW7B8Z/MP4f7PKOCVLjOvCgNY7gDLZhUZshCe9HBcM6oE9kEiNU3OJJu2p4x5B2PcNCIVVD0j4xcfdyk2JnRgrFbRBJ5oKXpU4oxedWIdhVjV74M/vBm9nOEEavPvqqTN+CvWTvmUaSNS0syTUoYWXZG5XyR3oOFJXnhue0UXGMhqnipbz7HPjT3ul2tDuLx+LTNIe4rHp377dh8KRTSGAz40dpjOGo1R14LNvu8kSSqaYvhm7WuPU46LI56DSwR7CNpYkJuiRarV/RQeoaRrOCVVn2B5jM="
script:
- "make all"
deploy:
- provider: script
  on:
    tags: true
  skip_cleanup: true
  script:
  - "make docker-deploy"

