---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespaceconfigs.openshift.bankdata.dk
spec:
  group: openshift.bankdata.dk
  names:
    kind: NamespaceConfig
    listKind: NamespaceConfigList
    plural: namespaceconfigs
    shortNames:
      - nscfg
      - nscfgs
    singular: namespaceconfig
  scope: Namespaced
  conversion:
    strategy: None
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: NamespaceConfig is a type to represent post-namespace creation configuration in Openshift
        type: object
        required:
          - metadata
          - spec
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            type: object
            required:
              - multicast
            properties:
              multicast:
                description: Multicast decides if multicast must be enabled on the namespace
                type: boolean
              extraAnnotations:
                description: Additional annotations to put on the namespace
                type: object
                x-kubernetes-preserve-unknown-fields: true
              extraLabels:
                description: Additional labels to put on the namespace
                type: object
                x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status of the namespace configuration
            type: object
            properties:
              observedGeneration:
                description: ObservedGeneration is the most recent generation observed
                  by the operator.
                type: integer
                format: int64
              message:
                description: Message describes the current state of the object in textual format
                type: string
              phase:
                description: Phase the configuation is in, one of ('New', 'Upgrading', 'UpgradeFailed', 'Succeeded')
                type: string
                enum:
                  - New
                  - Upgrading
                  - UpgradeFailed
                  - Succeeded
    served: true
    storage: true
    subresources:
      status: {}