---
apiVersion: openshift.bankdata.dk/v1
kind: NamespaceConfig
metadata:
  name: adpy
  namespace: adpy
spec:
  extraAnnotations:
    bankdata.dk/contact-owner: bduxyz
    bankdata.dk/contact-email: bdmxyz@bankdata.dk
    openshift.io/description: 'XYZ namespace'
  extraLabels:
    business-project: bankdata
  multicast: true
  owner: sorend
  email: sorend@gmail.com
  description: 'XYZ namespace 2'
