name: cd

on:
  schedule:
  - cron: '0 10 * * *' # every day at 10am
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_push:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.5
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v3.5.0
      with:
        images: |
          ghcr.io/sorend/namespace-config-controller
        tag-sha: true
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11
    - name: Login to ghcr
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build with gradle
      run: ./gradlew build
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        file: src/main/docker/Dockerfile.jvm
