name: cd-pr

on:
  pull_request:
    branches:
      - 'master'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v4.6.0
      with:
        images: |
          ghcr.io/sorend/namespace-config-controller
        tag-sha: true
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v2.9.1
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
    - name: Build with gradle
      run: ./gradlew build
    - name: Build with docker
      id: docker_build
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        push: false
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        file: src/main/docker/Dockerfile.jvm
